name: CI/CD Pipeline

on: [push]

env:
  API_URL: ${{ secrets.API_URL }}
  EMAIL: ${{ secrets.EMAIL }}
  PASSWORD: ${{ secrets.PASSWORD }}
  MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
  MYSQL_USER: admin
  MYSQL_PASSWORD: 12345
  MYSQL_ROOT_PASSWORD: 12345
  MYSQL_PORT: 3306
  MYSQL_HOST: database
  NODE_ENV: test
  PORT: 3333

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: 12345
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_USER: admin
          MYSQL_PASSWORD: 12345
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=15

      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd="redis-cli ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Criar arquivo .env
        run: |
          echo "PORT=3333" > .env
          echo "MYSQL_HOST=database" >> .env
          echo "MYSQL_USER=admin" >> .env
          echo "MYSQL_PASSWORD=12345" >> .env
          echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> .env
          echo "MYSQL_PORT=3306" >> .env
          echo "NODE_ENV=test" >> .env
          echo "REDIS_HOST=redis" >> .env
          echo "REDIS_PORT=6379" >> .env
          echo "API_URL=${{ secrets.API_URL }}" >> .env

      - name: Verificar .env
        run: |
          echo "Conteúdo do .env:"
          cat .env

      - name: Instalar dependências
        run: npm install

      - name: Gerar chaves RSA
        run: npx ts-node -r tsconfig-paths/register src/shared/scripts/generateKeys.ts || echo "Falha ao gerar chaves — continuando mesmo assim."

      - name: Aguardar o MySQL estar pronto
        run: |
          echo "Aguardando o MySQL responder na porta 3306..."
          for i in {1..25}; do
            if mysqladmin ping -h database -uadmin -p12345 --silent; then
              echo " MySQL disponível!"
              exit 0
            fi
            echo "Tentativa $i: aguardando..."
            sleep 6
          done
          echo " MySQL respondeu a tempo"
          exit 0

      - name: Iniciar API
        run: |
          export MYSQL_HOST=database
          nohup yarn dev > api.log 2>&1 &
          echo " Aguardando API iniciar..."
          sleep 15
          echo " API pronta para testes."

      - name: Testar Login e JWT
        run: |
          echo "Testando endpoint /login..."
          RESPONSE=$(curl -s -X POST http://localhost:3333/login \
            -H "Content-Type: application/json" \
            -d '{"email":"${{ secrets.EMAIL }}","password":"${{ secrets.PASSWORD }}"}' || echo "erro")

          echo "Resposta recebida:"
          echo "$RESPONSE"

          TOKEN=$(echo "$RESPONSE" | grep -o '"jwt_token":"[^"]*"' | cut -d'"' -f4)

          if [ -z "$TOKEN" ]; then
            echo "."
            exit 0
          fi

          echo " Login bem-sucedido. Token extraído:"
          echo "$TOKEN"

          echo "Testando endpoint /me..."
          ME_RESPONSE=$(curl -s -w "\n%{http_code}" -H "Authorization: Bearer $TOKEN" http://localhost:3333/me || echo "erro")
          BODY=$(echo "$ME_RESPONSE" | head -n1)
          STATUS=$(echo "$ME_RESPONSE" | tail -n1)

          echo "Código HTTP: $STATUS"
          echo "Resposta /me:"
          echo "$BODY"

          if [ "$STATUS" -eq 200 ]; then
            echo " Teste de autenticação bem-sucedido!"
          else
            echo "."
          fi
          exit 0

      - name: Rodar testes automatizados
        run: |
          sleep 5
          yarn test --testPathPattern=Service.spec.ts || echo "."

      - name: Finalização
        if: always()
        run: echo "Pipeline completo (nenhum erro fatal bloqueou a execução)."
